baseurl = "https://www.t-wie-tesla.de"
DefaultContentLanguage = "de"
title = "T wie Tesla"
theme = "hugo-future-imperfect-slim"
preserveTaxonomyNames = true
paginate = 20
pluralizeListTitles = false
disableLanguages = [""]
googleAnalytics = "UA-12561257-15"

[params]
    cssFiles = ["default", "css/custom.css"]
    jsFiles = ["default"]
    viewMorePostsLink = "/blog/"
    readingTime = true
    [params.meta]
        description = "Auf seinem Blog “T wie Tesla” schreibt Tesla-Fahrer Marcel über seine Erlebnisse mit seinem Model 3."
        author = "Marcel Kraus, Erftstadt"
        favicon = false
        svg = true
        faviconVersion = "1"
        msColor = "#ffffff" # Copy from the https://realfavicongenerator.net
        iOSColor = "#ffffff" # Copy from the https://realfavicongenerator.net
    [params.header]
        navbarTitle = "T wie Tesla"
        dynamicTitles = true
        searchMenu = true
        shareMenu = false
        languageMenu = false
    [params.intro]
        header = "T wie Tesla"
        paragraph = "Tagebuch eines Tesla-Fahrers…"
        rssIntro = true
        socialIntro = true
        [params.intro.pic]
            alt = "T wie Tesla – Tesla-Logo"
            shape = "circle"
            src = "/images/tesla-logo.jpg"
            width = "100"
    [params.sidebar]
        about = "“T wie Tesla” ist ein Blog von Marcel aus der Supercharger-Stadt Erftstadt bei Köln. Ein Tesla-Fan schreibt für Tesla-Fans über seine persönlichen Erfahrungen mit dem Model 3."
        postAmount = 10
        categories = false
        categoriesByCount = false
    [params.footer]
        rssFooter = true
        socialFooter = false

[menu]
    [[menu.main]]
        name = "Startseite"
        url = "/"
        identifier = "fas fa-home"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        identifier = "far fa-newspaper"
        weight = 2
    [[menu.main]]
        name = "Kategorien"
        url = "/kategorien/"
        identifier = "fas fa-sitemap"
        weight = 3
    [[menu.main]]
        name = "Über mich"
        url = "/ueber-mich/"
        identifier = "far fa-id-card"
        weight = 4
    [[menu.main]]
        name = "Impressum"
        url = "/impressum/"
        identifier = "far fa-list"
        weight = 5

[permalinks]
    categories = "/kategorien/:slug/"

[social]
    github = "marcelkraus/t-wie-tesla"
    twitter = "twietesla"
